# Generated by Django 5.0.6 on 2026-05-21 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('email_sent', 'Email Sent'), ('whatsapp_sent', 'WhatsApp Sent'), ('status_change', 'Status Change'), ('settings_update', 'Settings Update'), ('rates_refresh', 'Rates Refresh')], max_length=30)),
                ('target', models.CharField(blank=True, help_text='Target object identifier (e.g., transaction ID)', max_length=255)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin Audit',
                'verbose_name_plural': 'Admin Audits',
                'ordering': ['-created_at'],
            },
        ),
    ]
