# Generated by Django 5.0.6 on 2026-05-21 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeesGrid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corridor', models.CharField(help_text='Transfer corridor (e.g., EUR_XAF, EUR_XOF)', max_length=10)),
                ('currency', models.CharField(default='EUR', help_text='Currency for the amount range', max_length=3)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, help_text='Fixed fee in EUR', max_digits=8)),
                ('fee_percent', models.DecimalField(decimal_places=2, default=0, help_text='Percentage fee (e.g., 2.50 for 2.5%)', max_digits=5)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fees Grid',
                'verbose_name_plural': 'Fees Grid',
                'ordering': ['corridor', 'min_amount'],
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('key', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('value', models.JSONField()),
                ('description', models.TextField(blank=True)),
                ('is_public', models.BooleanField(default=False, help_text='If True, this setting is accessible without authentication')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
                'ordering': ['key'],
            },
        ),
    ]
