# Generated by Django 5.0.6 on 2026-05-21 16:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('corridor', models.CharField(choices=[('EUR_XAF', 'EUR -> XAF (FCFA CEMAC)'), ('EUR_XOF', 'EUR -> XOF (FCFA UEMOA)')], max_length=10)),
                ('amount_sent', models.DecimalField(decimal_places=2, help_text='Amount in EUR', max_digits=12)),
                ('amount_received', models.DecimalField(decimal_places=2, help_text='Amount in target currency', max_digits=14)),
                ('fees', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('rate_applied', models.DecimalField(decimal_places=6, max_digits=12)),
                ('include_airtel', models.BooleanField(default=False)),
                ('sender_name', models.CharField(max_length=200)),
                ('sender_phone', models.CharField(max_length=20)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('beneficiary_name', models.CharField(max_length=200)),
                ('beneficiary_phone', models.CharField(max_length=20)),
                ('beneficiary_city', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('pending_contact', 'En attente de contact'), ('in_progress', 'En cours'), ('completed', 'Terminee'), ('cancelled', 'Annulee')], default='pending_contact', max_length=20)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
