# Generated by Django 5.0.6 on 2026-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulator', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='beneficiary_city',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='include_airtel',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='rate_applied',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_email',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_name',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='sender_phone',
        ),
        migrations.AddField(
            model_name='transaction',
            name='beneficiary_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_received',
            field=models.CharField(default='XAF', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='currency_sent',
            field=models.CharField(default='EUR', max_length=3),
        ),
        migrations.AddField(
            model_name='transaction',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fees_adoro',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='fees_airtel',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='rate_used',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='total_to_send',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, max_digits=14),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_sent',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='beneficiary_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='corridor',
            field=models.CharField(max_length=10),
        ),
    ]
