# Generated by Django 5.0.6 on 2026-05-21 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RatesHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('source', models.CharField(choices=[('exchangerate_host', 'exchangerate.host'), ('frankfurter', 'frankfurter.dev'), ('static', 'Static (fixed FCFA rate)')], max_length=30)),
                ('base_currency', models.CharField(default='EUR', max_length=3)),
                ('rates', models.JSONField(help_text='JSON object with currency codes as keys and rates as values')),
            ],
            options={
                'verbose_name': 'Rates History',
                'verbose_name_plural': 'Rates History',
                'ordering': ['-date', '-fetched_at'],
                'unique_together': {('date', 'source')},
            },
        ),
    ]
