# Generated by Django 5.0.6 on 2026-05-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rateshistory',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='rateshistory',
            name='source',
            field=models.CharField(choices=[('exchangeratesapi.io', 'exchangeratesapi.io'), ('frankfurter', 'frankfurter.dev'), ('static', 'Static (fixed FCFA rate)')], max_length=30),
        ),
    ]
